### ISSUE TITLE
Incompatible with current nginx (1.14.0)

### ISSUE THREAD

**Issue by eutychus** [kaltura/nginx-parallel-module#4]
We have used this module with earlier versions.
I know it works with 1.11.4.

Our application failed after upgrading to 1.14.0.  I simplified the configuration to essentially what is in the documentation and get the same error.

~~~~
2018/04/25 09:44:27 [error] 10780#10780: *1 too big subrequest response: 131072 while sending to client, client: 127.0.0.1, server: , request: "GET /parallel/demo1/random.mp4 HTTP/1.1", subrequest: "/proxy/parallel/demo1/random.mp4", upstream: "http://104.217.251.190:80/demo1/random.mp4", host: "localhost"
2018/04/25 09:44:28 [error] 10785#10785: *10 too big subrequest response: 131072 while sending to client, client: 127.0.0.1, server: , request: "GET /parallel/demo1/random.mp4 HTTP/1.1", subrequest: "/proxy/parallel/demo1/random.mp4", upstream: "http://104.217.251.190:80/demo1/random.mp4", host: "localhost"
~~~~

--- Configuration ---

~~~~ user nginx; 
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
        
events {        
        worker_connections 6000;
}       

#include rtmp.conf;
                
http {  

upstream backend {
        server downloads.lightcastmedia.com:80;
        keepalive 32;
}

server {

        location /parallel {
                parallel /proxy;
        }

        location /proxy/parallel/ {
                proxy_pass http://backend/;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $http_host;

                internal;
        }
}
}
~~~~

**Comment by erankor** [comment]
Try adding `subrequest_output_buffer_size 128k` to nginx.conf, it's a new directive that was added in 1.13.10

**Comment by eutychus** [comment]
Thanks for the quick response!  It does seem to work as long as `subrequest_output_buffer_size ` is set larger than `parallel_max_chunk_size`.  Can you clarify how this change might effect performance and memory use?  We were previously using a max chunk size of 1024k.  Was it previously allocating a 1MB buffer for each fiber?

**Comment by erankor** [comment]
Yes, it was allocating 1MB per fiber. 
I don't think there will be any effect due to the addition of subrequest_output_buffer_size, it's just some extra validation that was added in this version of nginx.

**Comment by eutychus** [comment]
I appreciate the help.
